### ISSUE TITLE
how can I edit my own images?

### ISSUE THREAD

**Issue by joshyyas** [Psarpei/GanVinci#4]
First, I appreciate your great work

I think the model generates the latent and edits

then, can you tell me how I can edit my images?

Thanks in advance

**Comment by Psarpei** [comment]
Hi,

to edit your own images you need to apply a technique called gan inversion. With it you obtain a latent code for your image which can then be edited. There are a lot of gan inversion approaches with open source repositories, all with it's own pros and cons.

**Comment by joshyyas** [comment]
thanks for the quick response
